image: node:12-stretch

pages:
  tags:
    - docker
  stage: deploy
  script:
    - npm ci
    - npm run build
    - mkdir public
    - cp -r build/* public
  artifacts:
    paths:
      - public
  only:
    - master
